//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDBXEditor.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Definitions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Definitions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WDBXEditor.Core.Resources.Definitions", typeof(Definitions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;AreaMIDIAmbiences&quot; Build=&quot;3368&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;DaySequence&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;NightSequence&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;DLSFile&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Volume&quot; Type=&quot;float&quot; /&gt;
        ///  &lt;/Table&gt;
        ///  &lt;Table Name=&quot;AreaPOI&quot; Build=&quot;3368&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alpha_0_5_3__3368_ {
            get {
                return ResourceManager.GetString("Alpha_0_5_3__3368_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instanc&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Name=&quot;Achievement&quot; Build=&quot;26231&quot;&gt;
        ///		&lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///		&lt;Field Name=&quot;InstanceId&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;Category&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;UiOrder&quot; Type=&quot;ushort&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BfA_8_0_1__26231_ {
            get {
                return ResourceManager.GetString("BfA_8_0_1__26231_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instanc&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;Table Name=&quot;Achievement&quot; Build=&quot;26367&quot;&gt;
        ///   &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///   &lt;Field Name=&quot;InstanceId&quot; Type=&quot;ushort&quot; /&gt;
        ///   &lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///   &lt;Field Name=&quot;Category&quot; Type=&quot;ushort&quot; /&gt;
        ///   &lt;Field Name=&quot;UiOrder&quot; Type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BfA_8_0_1__26367_ {
            get {
                return ResourceManager.GetString("BfA_8_0_1__26367_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instanc&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;Table Name=&quot;Achievement&quot; Build=&quot;26806&quot;&gt;
        ///   &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///   &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///   &lt;Field Name=&quot;InstanceId&quot; Type=&quot;short&quot; /&gt;
        ///   &lt;Field Name=&quot;Faction&quot; Type=&quot;byte&quot; /&gt;
        ///   &lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///   &lt;Field Name=&quot;Categor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BfA_8_0_1__26806_ {
            get {
                return ResourceManager.GetString("BfA_8_0_1__26806_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Name=&quot;Achievement&quot; Build=&quot;27075&quot;&gt;
        ///		&lt;Field Name=&quot;Description_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Title_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Reward_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///		&lt;Field Name=&quot;Instance_ID&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Faction&quot; Type=&quot;byte&quot; /&gt;
        ///		&lt;Field Name=&quot;Supercedes&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BfA_8_0_1__27075_ {
            get {
                return ResourceManager.GetString("BfA_8_0_1__27075_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;32978&quot;&gt;
        ///    &lt;Field Name=&quot;Description_Lang&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Title_Lang&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Reward_Lang&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Instance_ID&quot; Type=&quot;short&quot; /&gt;
        ///    &lt;Field Name=&quot;Faction&quot; Type=&quot;byte&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;short&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BfA_8_2_5__32978_ {
            get {
                return ResourceManager.GetString("BfA_8_2_5__32978_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;15595&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;FactionFlag&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;MapId&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;ParentAchievement&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Name&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;CategoryId&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cata_4_3_4__15595_ {
            get {
                return ResourceManager.GetString("Cata_4_3_4__15595_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;AnimationData&quot; Build=&quot;5875&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Name&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;WeaponFlags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;BodyFlags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Fallback&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;BehaviourID&quot; Type=&quot;int&quot; /&gt;
        ///  &lt;/Table&gt;
        ///  &lt;Table Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classic_1_12_1__5875_ {
            get {
                return ResourceManager.GetString("Classic_1_12_1__5875_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;22248&quot;&gt;
        ///    &lt;Field Name=&quot;Field00&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field04&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field08&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Field0C&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field10&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field12&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field14&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field16&quot; T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_0_3__22248_ {
            get {
                return ResourceManager.GetString("Legion_7_0_3__22248_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;22578&quot;&gt;
        ///    &lt;Field Name=&quot;Field00&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field04&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field08&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Field0C&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Field10&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field12&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field14&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Field16&quot; T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_1_0__22578_ {
            get {
                return ResourceManager.GetString("Legion_7_1_0__22578_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;23835&quot;&gt;
        ///    &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;MapID&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;UIOrder&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_2_0__23835_ {
            get {
                return ResourceManager.GetString("Legion_7_2_0__23835_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;24492&quot;&gt;
        ///    &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;MapID&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;UIOrder&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_3_0__24492_ {
            get {
                return ResourceManager.GetString("Legion_7_3_0__24492_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;24793&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; AutoGenerate=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Data&quot; Type=&quot;string&quot; ArraySize=&quot;2&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Instance_Id&quot; Type=&quot;short&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_3_0__24793_ {
            get {
                return ResourceManager.GetString("Legion_7_3_0__24793_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Name=&quot;Achievement&quot; Build=&quot;25632&quot;&gt;
        ///		&lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Reward&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Flags&quot; Type=&quot;uint&quot; /&gt;
        ///		&lt;Field Name=&quot;MapID&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;Supercedes&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;Category&quot; Type=&quot;ushort&quot; /&gt;
        ///		&lt;Field Name=&quot;UIOrder&quot; Type=&quot;ushort&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_3_5__25632_ {
            get {
                return ResourceManager.GetString("Legion_7_3_5__25632_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Name=&quot;Achievement&quot; Build=&quot;26654&quot;&gt;
        ///		&lt;Field Name=&quot;Title_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Description_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Reward_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///		&lt;Field Name=&quot;Instance_ID&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Supercedes&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Category&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Ui_Order [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_3_5__26654_ {
            get {
                return ResourceManager.GetString("Legion_7_3_5__26654_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Name=&quot;Achievement&quot; Build=&quot;26972&quot;&gt;
        ///		&lt;Field Name=&quot;Title_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Description_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Reward_Lang&quot; Type=&quot;string&quot; /&gt;
        ///		&lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///		&lt;Field Name=&quot;Instance_ID&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Supercedes&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Category&quot; Type=&quot;short&quot; /&gt;
        ///		&lt;Field Name=&quot;Ui_Order [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legion_7_3_5__26972_ {
            get {
                return ResourceManager.GetString("Legion_7_3_5__26972_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;18414&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Faction&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Instance_Id&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Description&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoP_5_4_8__18414_ {
            get {
                return ResourceManager.GetString("MoP_5_4_8__18414_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Offsets {
            get {
                object obj = ResourceManager.GetObject("Offsets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;AnimationData&quot; Build=&quot;8606&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Name&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;WeaponFlags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;BodyFlags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Fallback&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;BehaviourID&quot; Type=&quot;int&quot; /&gt;
        ///  &lt;/Table&gt;
        ///  &lt;Table Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TBC_2_4_3__8606_ {
            get {
                return ResourceManager.GetString("TBC_2_4_3__8606_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Definition&gt;
        ///  &lt;Table Name=&quot;CreatureCache&quot; Build=&quot;12340&quot;&gt;
        ///    &lt;Field Name=&quot;Entry&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Name&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Name2&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Name3&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Name4&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;SubName&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;IconName&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Flags&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Type&quot; Type=&quot;uint&quot; /&gt;
        ///    &lt;Field Name=&quot;Family [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WDB {
            get {
                return ResourceManager.GetString("WDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;21742&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Faction&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Instance_Id&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Title_Lang&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Description_Lang&quot; Type=&quot;string&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Fiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoD_6_2_4__21742_ {
            get {
                return ResourceManager.GetString("WoD_6_2_4__21742_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Definition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Name=&quot;Achievement&quot; Build=&quot;12340&quot;&gt;
        ///    &lt;Field Name=&quot;ID&quot; Type=&quot;int&quot; IsIndex=&quot;true&quot; /&gt;
        ///    &lt;Field Name=&quot;Faction&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Instance_Id&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Supercedes&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name=&quot;Title_Lang&quot; Type=&quot;loc&quot; /&gt;
        ///    &lt;Field Name=&quot;Description_Lang&quot; Type=&quot;loc&quot; /&gt;
        ///    &lt;Field Name=&quot;Category&quot; Type=&quot;int&quot; /&gt;
        ///    &lt;Field Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WotLK_3_3_5__12340_ {
            get {
                return ResourceManager.GetString("WotLK_3_3_5__12340_", resourceCulture);
            }
        }
    }
}
